workflows:
  flutter-android-beta:
    name: HRMate Native Android Beta (Release APK)
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      flutter: default
      java: 17
      vars:
        PACKAGE_NAME: "in.flavorflow.hrmate.beta"
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Flutter Pub Get
        script: |
          cd mobile
          flutter pub get

      - name: Flutter Analyze
        script: |
          cd mobile
          flutter analyze

      - name: Flutter Test
        script: |
          cd mobile
          flutter test

      - name: Build Native Beta Release APK
        script: |
          cd mobile
          flutter build apk --release --flavor beta \
            --dart-define=HRMATE_API=https://hr.flavorflow.co.in/api/v1/mobile

    artifacts:
      - mobile/build/app/outputs/flutter-apk/*.apk
      - mobile/build/app/outputs/bundle/betaRelease/*.aab

    publishing:
      email:
        recipients:
          - manjotkhehra025@gmail.com
        notify:
          failure: true
          success: true

  flutter-android-prod:
    name: HRMate Native Android Prod (Release APK & AAB)
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      flutter: default
      java: 17
      vars:
        PACKAGE_NAME: "in.flavorflow.hrmate"
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Flutter Pub Get
        script: |
          cd mobile
          flutter pub get

      - name: Build Native Prod Release APK
        script: |
          cd mobile
          flutter build apk --release --flavor prod \
            --dart-define=HRMATE_API=https://hr.flavorflow.co.in/api/v1/mobile

      - name: Build Native Prod Release AppBundle
        script: |
          cd mobile
          flutter build appbundle --release --flavor prod \
            --dart-define=HRMATE_API=https://hr.flavorflow.co.in/api/v1/mobile

    artifacts:
      - mobile/build/app/outputs/flutter-apk/*.apk
      - mobile/build/app/outputs/bundle/prodRelease/*.aab

    publishing:
      email:
        recipients:
          - manjotkhehra025@gmail.com
        notify:
          failure: true
          success: true
